---
name: CICD

'on':  # quoted so it is not considered a boolean
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, edited, synchronize ]

jobs:
  pr-name:
    name: Conventional commits
    uses: gcs-sre/.github/.github/workflows/pr-name.yml@main
  linters:
    name: Linters
    uses: gcs-sre/.github/.github/workflows/linters.yml@main
